image: alpine

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOXYGEN_DIR: Documentation/doxygen


build_docs:
  stage: build
  before_script:
    - apk update
    - apk add git doxygen ttf-freefont graphviz # pdf2svg
  script:
    - doxygen $DOXYGEN_DIR/Doxyfile
  artifacts:
    paths:
      - $DOXYGEN_DIR/html


github_pages:
  stage: deploy
  only:
    refs:
      - master
  variables:
    GIT_STRATEGY: none
  before_script:
    - apk update && apk add git
  script:
    - git init
    - git remote add upstream $GIT_UPSTREAM_URL
    - git fetch upstream
    - git checkout gh-pages
    - git pull --ff-only
    - git stash push --all -- $DOXYGEN_DIR    # stash artifacts from previous stage
    - rm -rf *                                # remove old documentation
    - git stash pop                           # restore artifacts from previous stage
    - mv $DOXYGEN_DIR/html/* .
    - rm -rf $DOXYGEN_DIR
    - git add .
    - git config user.email $DOCS_COMMIT_EMAIL
    - git config user.name $DOCS_COMMIT_NAME
    - git commit -m "Generated Documentation" -m "Build from $CI_SERVER_NAME pipeline $CI_PIPELINE_ID"
    - git push upstream HEAD:gh-pages
