image: alpine

stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: normal
  DOXYGEN_DIR: Documentation/doxygen
  PROJECT_DIR: Dixit


build_docs:
  stage: build
  only:
    changes:
      - $PROJECT_DIR
  before_script:
    - apk update
    - apk add git doxygen ttf-freefont graphviz # pdf2svg
  script:
    - doxygen $DOXYGEN_DIR/Doxyfile
  artifacts:
    paths:
      - $DOXYGEN_DIR/html


github_pages:
  stage: deploy
  only:
    changes:
      - $PROJECT_DIR
    refs:
      - master
  before_script:
    - apk update && apk add git
  script:
    - git remote add upstream $GIT_UPSTREAM_URL
    - git fetch upstream
    - git checkout gh-pages
    - git pull --ff-only
    - mv -f $DOXYGEN_DIR/html/* .
    - rm -rf $DOXYGEN_DIR
    - git add .
    - git config user.email $DOCS_COMMIT_EMAIL
    - git config user.name $DOCS_COMMIT_NAME
    - git commit -m "Generated Documentation\n\nBuild from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push upstream HEAD:gh-pages
